jobs:
  app-dir: ~/project/backend/
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/backend/
          cache-path: ~/project/backend/node_modules
          override-ci-command: npm install
      - run: cd ~/project/backend/ ; npm run test
  run:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/backend/
          cache-path: ~/project/backend/node_modules
          override-ci-command: npm install
      - run: cd ~/project/backend/ ; npm start
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test:
    jobs:
      - test
      - run