jobs:
  test:
    working_directory: /home/circleci/project/backend/
    executor: node/default
    steps:
      - checkout
      - run: cd /backend/
      - node/install-packages:
          app-dir: ~/project/backend/
          cache-path: ~/project/backend/node_modules
          override-ci-command: npm install
      - run: mocha server.test.js
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  test-and-deploy:
    jobs:
      - node/test