jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/backend/node_modules
          override-ci-command: npm install
      - run: mocha server.test.js
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  test-and-deploy:
    jobs:
      - node/test